name: Makefile
on: 
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # updated on Jan 16
      
      
      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@40677d36a502eb2cf0fb808cc9dec31bf6152638 # v2.28.0 
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-openssl
            mingw-w64-ucrt-x86_64-sqlite
            make
            
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install build-essential libssl-dev openssl sqlite3

        
      - if: matrix.os == 'windows-latest'
        run: make -j$(nproc)
        shell: msys2 {0}
      
      - if: matrix.os == 'ubuntu-latest'
        run: make -j$(nproc)
        # assume bash
